services:
  local-language-model:
    image: ghcr.io/ggml-org/llama.cpp:full-cuda13
    devices:
      - nvidia.com/gpu=all
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models:ro,z
    restart: always
    command: [
        "-s",
        "-m",
        "/models/Qwythos-9B-Claude-Mythos-5-1M-MTP-Q4_K_M.gguf",
        # "--reasoning",
        # "off",
        "--cache-type-k",
        "q8_0",
        "--cache-type-v",
        "q4_0",
        "--spec-type",
        "draft-mtp",
        "--spec-draft-n-max",
        "4",
        "-fa",
        "on",
        "-c",
        "32000",
        "-ngl",
        "99",
        "--port",
        "8080",
        "--host",
        "0.0.0.0",
      ]
